# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'boutiq' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for boutiq
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'boutiqTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
